package com.pearl.normandy.usergroup;

/**
 * UserGroup generated by MyEclipse Persistence Tools
 */

public class UserGroupTo extends UserGroup {	
	private static final long serialVersionUID = -566578554864264041L;	
}